import type {
  Alert,
  Bootstrap,
  Cluster,
  Host,
  NetworkSummary,
  PlatformOperator,
  ServiceStatus,
  StorageBackup,
  TimeSeries,
  Weather,
  Workload,
} from './contracts.js';
import { healthyIndoorFixture } from './indoor-fixtures.js';

export const FIXTURE_TIME = '2026-07-19T12:00:00.000Z';

const metadata = (
  source: string,
  freshness: 'CURRENT' | 'STALE' | 'NO_DATA' | 'NOT_PROVISIONED' | 'NOT_SUPPORTED',
  severity: 'OK' | 'INFO' | 'WARN' | 'CRIT',
  message?: string,
) => ({
  source,
  observedAt: FIXTURE_TIME,
  freshness,
  severity,
  ...(message ? { message } : {}),
});

function fixtureCoreSeries(host: string, cores: number[], freshness: 'CURRENT' | 'STALE', severity: 'OK' | 'WARN'): TimeSeries[] {
  const timestamps = ['2026-07-19T11:45:00.000Z', '2026-07-19T11:50:00.000Z', '2026-07-19T11:55:00.000Z', FIXTURE_TIME];
  return cores.map((current, coreIndex) => ({
    metric: `${host} CORE ${coreIndex}`,
    unit: '%',
    window: '15m',
    points: timestamps.map((timestamp, sampleIndex) => ({ timestamp, value: sampleIndex === timestamps.length - 1 ? current : Math.max(0, current + ((sampleIndex - 1) * 5) + ((coreIndex % 3) - 1) * 3) })),
    metadata: metadata('fixture-glances', freshness, severity),
  }));
}

export const fixtureAlerts: Alert[] = [
  {
    id: 'alert-k3s-worker-warning',
    name: 'K3sWorkerCapacity',
    severity: 'WARN',
    summary: 'k8s-worker-02 memory is approaching its configured threshold.',
    startsAt: '2026-07-19T11:42:00.000Z',
    source: 'fixture-alertmanager',
    metadata: metadata('fixture-alertmanager', 'CURRENT', 'WARN'),
  },
];

export const fixtureTimeSeries: TimeSeries[] = [
  {
    metric: 'pve-01 CPU',
    unit: '%',
    window: '15m',
    points: [
      { timestamp: '2026-07-19T11:45:00.000Z', value: 28 },
      { timestamp: '2026-07-19T11:50:00.000Z', value: 35 },
      { timestamp: '2026-07-19T11:55:00.000Z', value: 31 },
      { timestamp: FIXTURE_TIME, value: 42 },
    ],
    metadata: metadata('fixture-prometheus', 'CURRENT', 'OK'),
  },
  ...fixtureCoreSeries('pve-01', [38, 42, 35, 47, 39, 43, 41, 45], 'CURRENT', 'OK'),
  ...fixtureCoreSeries('pve-02', [62, 71, 64, 69, 66, 73, 61, 70], 'STALE', 'WARN'),
];

export const fixtureHosts: Host[] = [
  {
    id: 'pve-01',
    name: 'pve-01',
    kind: 'PROXMOX',
    cpuPercent: 42,
    memoryPercent: 58,
    memoryUsedBytes: 9_985_799_680,
    memoryTotalBytes: 17_179_869_184,
    diskUsedBytes: 1_693_186_048_512,
    diskTotalBytes: 2_199_023_255_552,
    diskIoPercent: 46,
    cpuModel: 'AMD EPYC',
    cpuCorePercentages: [38, 42, 35, 47, 39, 43, 41, 45],
    loadAverage: [0.42, 0.38, 0.31],
    cpuClockMhz: 3_100,
    powerWatts: 82,
    swapUsedBytes: 268_435_456,
    swapTotalBytes: 4_294_967_296,
    uptimeSeconds: 1_555_200,
    runningVmCount: 8,
    stoppedVmCount: 2,
    runningContainerCount: 4,
    stoppedContainerCount: 1,
    runningPodCount: null,
    podCapacity: null,
    temperatureCelsius: 47,
    networkIngressBitsPerSecond: 120_000_000,
    networkEgressBitsPerSecond: 80_000_000,
    networkTotalBytes: 1_374_389_534_720,
    metadata: metadata('fixture-prometheus', 'CURRENT', 'OK'),
  },
  {
    id: 'pve-02',
    name: 'pve-02',
    kind: 'PROXMOX',
    cpuPercent: 67,
    memoryPercent: 76,
    memoryUsedBytes: 13_099_515_904,
    memoryTotalBytes: 17_179_869_184,
    diskUsedBytes: 1_407_374_883_840,
    diskTotalBytes: 2_199_023_255_552,
    diskIoPercent: 31,
    cpuModel: 'Intel Xeon',
    cpuCorePercentages: [62, 71, 64, 69, 66, 73, 61, 70],
    loadAverage: [0.78, 0.71, 0.66],
    cpuClockMhz: 2_800,
    powerWatts: 61,
    swapUsedBytes: 805_306_368,
    swapTotalBytes: 4_294_967_296,
    uptimeSeconds: 604_800,
    runningVmCount: 6,
    stoppedVmCount: 1,
    runningContainerCount: 2,
    stoppedContainerCount: 0,
    runningPodCount: null,
    podCapacity: null,
    temperatureCelsius: 59,
    networkIngressBitsPerSecond: 90_000_000,
    networkEgressBitsPerSecond: 45_000_000,
    networkTotalBytes: 824_633_720_832,
    metadata: metadata('fixture-prometheus', 'STALE', 'WARN', 'Last sample is 42 seconds old.'),
  },
  {
    id: 'k3s-control-01',
    name: 'k3s-control-01',
    kind: 'K3S_NODE',
    cpuPercent: 36,
    memoryPercent: 52,
    memoryUsedBytes: null,
    memoryTotalBytes: null,
    diskUsedBytes: null,
    diskTotalBytes: null,
    diskIoPercent: null,
    cpuModel: null,
    cpuCorePercentages: null,
    loadAverage: null,
    cpuClockMhz: null,
    powerWatts: null,
    swapUsedBytes: null,
    swapTotalBytes: null,
    uptimeSeconds: null,
    runningVmCount: null,
    stoppedVmCount: null,
    runningContainerCount: null,
    stoppedContainerCount: null,
    runningPodCount: null,
    podCapacity: null,
    temperatureCelsius: null,
    networkIngressBitsPerSecond: null,
    networkEgressBitsPerSecond: null,
    networkTotalBytes: null,
    metadata: metadata('fixture-k3s-api', 'CURRENT', 'OK'),
  },
  {
    id: 'k3s-worker-01',
    name: 'k3s-worker-01',
    kind: 'K3S_NODE',
    cpuPercent: 48,
    memoryPercent: 63,
    memoryUsedBytes: null,
    memoryTotalBytes: null,
    diskUsedBytes: null,
    diskTotalBytes: null,
    diskIoPercent: null,
    cpuModel: null,
    cpuCorePercentages: null,
    loadAverage: null,
    cpuClockMhz: null,
    powerWatts: null,
    swapUsedBytes: null,
    swapTotalBytes: null,
    uptimeSeconds: null,
    runningVmCount: null,
    stoppedVmCount: null,
    runningContainerCount: null,
    stoppedContainerCount: null,
    runningPodCount: null,
    podCapacity: null,
    temperatureCelsius: null,
    networkIngressBitsPerSecond: null,
    networkEgressBitsPerSecond: null,
    networkTotalBytes: null,
    metadata: metadata('fixture-k3s-api', 'CURRENT', 'OK'),
  },
  {
    id: 'k3s-worker-02',
    name: 'k3s-worker-02',
    kind: 'K3S_NODE',
    cpuPercent: 58,
    memoryPercent: 86,
    memoryUsedBytes: null,
    memoryTotalBytes: null,
    diskUsedBytes: null,
    diskTotalBytes: null,
    diskIoPercent: null,
    cpuModel: null,
    cpuCorePercentages: null,
    loadAverage: null,
    cpuClockMhz: null,
    powerWatts: null,
    swapUsedBytes: null,
    swapTotalBytes: null,
    uptimeSeconds: null,
    runningVmCount: null,
    stoppedVmCount: null,
    runningContainerCount: null,
    stoppedContainerCount: null,
    runningPodCount: null,
    podCapacity: null,
    temperatureCelsius: null,
    networkIngressBitsPerSecond: null,
    networkEgressBitsPerSecond: null,
    networkTotalBytes: null,
    metadata: metadata('fixture-k3s-api', 'CURRENT', 'WARN', 'Memory pressure warning.'),
  },
  ...(['okd-cp-01', 'okd-cp-02', 'okd-cp-03'] as const).map((name) => ({
    id: name,
    name,
    kind: 'OKD_NODE' as const,
    cpuPercent: name === 'okd-cp-01' ? 18 : name === 'okd-cp-02' ? 23 : 16,
    memoryPercent: name === 'okd-cp-01' ? 42 : name === 'okd-cp-02' ? 38 : 44,
    memoryUsedBytes: name === 'okd-cp-01' ? 14_431_256_576 : name === 'okd-cp-02' ? 26_111_344_640 : 30_237_982_720,
    memoryTotalBytes: name === 'okd-cp-01' ? 34_359_738_368 : 68_719_476_736,
    diskUsedBytes: name === 'okd-cp-01' ? 37_163_175_936 : name === 'okd-cp-02' ? 51_325_435_904 : 48_677_601_280,
    diskTotalBytes: 999_178_825_728,
    diskIoPercent: name === 'okd-cp-03' ? 2.4 : 2.6,
    cpuModel: 'AMD Ryzen 5 PRO 5650GE · 6C/12T',
    cpuCorePercentages: [8, 12, 6, 9, 11, 7, 5, 8, 10, 6, 9, 7],
    loadAverage: [0.62, 0.58, 0.51] as [number, number, number],
    cpuClockMhz: null,
    powerWatts: name === 'okd-cp-02' ? 27.2 : 21.8,
    swapUsedBytes: 0,
    swapTotalBytes: 0,
    uptimeSeconds: name === 'okd-cp-01' ? 161_353 : name === 'okd-cp-02' ? 164_717 : 163_143,
    runningVmCount: null,
    stoppedVmCount: null,
    runningContainerCount: name === 'okd-cp-01' ? 64 : name === 'okd-cp-02' ? 132 : 106,
    stoppedContainerCount: name === 'okd-cp-01' ? 42 : name === 'okd-cp-02' ? 88 : 44,
    runningPodCount: name === 'okd-cp-01' ? 35 : name === 'okd-cp-02' ? 83 : 55,
    podCapacity: 250,
    temperatureCelsius: name === 'okd-cp-01' ? 45.4 : 55.9,
    networkIngressBitsPerSecond: name === 'okd-cp-01' ? 1_562_828 : name === 'okd-cp-02' ? 3_861_013 : 2_724_760,
    networkEgressBitsPerSecond: name === 'okd-cp-01' ? 2_714_027 : name === 'okd-cp-02' ? 2_665_116 : 2_817_471,
    networkTotalBytes: name === 'okd-cp-01' ? 160_578_052_807 : name === 'okd-cp-02' ? 250_006_355_421 : 198_545_040_757,
    metadata: metadata('fixture-okd-api', 'CURRENT', 'OK'),
  })),
];

export const fixtureClusters: Cluster[] = [
  {
    id: 'k3s',
    name: 'k3s',
    platform: 'K3S',
    nodeCount: 3,
    readyNodeCount: 3,
    workloadCount: 18,
    cpuCapacityCores: 12,
    cpuUsedCores: 5.4,
    memoryCapacityBytes: 34_359_738_368,
    memoryUsedBytes: 21_474_836_480,
    metadata: metadata('fixture-k3s-api', 'CURRENT', 'OK'),
  },
  {
    id: 'okd',
    name: 'OKD',
    platform: 'OKD',
    nodeCount: 3,
    readyNodeCount: 3,
    workloadCount: 142,
    cpuCapacityCores: 18,
    cpuUsedCores: 3.4,
    memoryCapacityBytes: 171_798_691_840,
    memoryUsedBytes: 70_780_583_936,
    metadata: metadata('fixture-okd-api', 'CURRENT', 'OK'),
  },
];

export const fixtureWorkloads: Workload[] = [
  {
    id: 'k3s:deployment:argocd:argocd-server', name: 'argocd-server', clusterId: 'k3s', namespace: 'argocd', readyReplicas: 1, desiredReplicas: 1, href: 'https://argocd.lab.seandre.dev',
    metadata: metadata('fixture-k3s-api', 'CURRENT', 'OK'),
  },
  {
    id: 'k3s:deployment:homelab:homepage', name: 'homepage', clusterId: 'k3s', namespace: 'homelab', readyReplicas: 2, desiredReplicas: 2, href: 'https://argocd.lab.seandre.dev',
    metadata: metadata('fixture-k3s-api', 'CURRENT', 'OK'),
  },
  {
    id: 'k3s:deployment:apps:koreader-sync', name: 'koreader-sync', clusterId: 'k3s', namespace: 'apps', readyReplicas: 0, desiredReplicas: 1, href: 'https://argocd.lab.seandre.dev',
    metadata: metadata('fixture-k3s-api', 'CURRENT', 'WARN', 'Deployment is waiting for a ready replica.'),
  },
];

export const fixturePlatformOperators: PlatformOperator[] = [
  { id: 'okd:operator:kube-apiserver', clusterId: 'okd', name: 'kube-apiserver', version: '4.22.0-okd-scos.7', available: true, progressing: false, degraded: false, metadata: metadata('fixture-okd-api', 'CURRENT', 'OK') },
  { id: 'okd:operator:ingress', clusterId: 'okd', name: 'ingress', version: '4.22.0-okd-scos.7', available: true, progressing: false, degraded: false, metadata: metadata('fixture-okd-api', 'CURRENT', 'OK') },
  { id: 'okd:operator:storage', clusterId: 'okd', name: 'storage', version: '4.22.0-okd-scos.7', available: true, progressing: false, degraded: false, metadata: metadata('fixture-okd-api', 'CURRENT', 'OK') },
];

export const fixtureNetwork: NetworkSummary = {
  gatewayLatencyMs: 1.4,
  gatewayLatencyProtocol: 'ICMP',
  internetLatencyMs: 18.2,
  internetLatencyProtocol: 'HTTPS',
  ingressVip: '192.168.40.30',
  ingressVips: ['192.168.40.30', '192.168.40.29', '192.168.40.31'],
  unifi: {
    controller: null,
    status: null,
    metadata: metadata('fixture-unifi', 'NOT_SUPPORTED', 'INFO', 'Local UniFi read-only API capability has not been verified.'),
  },
  udm: {
    wanDownloadMbps: 42.8,
    wanUploadMbps: 7.3,
    wanTotalBytes: 245_233_186_461,
    latencyMs: 11,
    cpuPercent: 8.2,
    memoryPercent: 74.5,
    temperatureCelsius: 43.5,
    uptimeSeconds: 530_660,
    clientCount: 19,
    metadata: metadata('fixture-unpoller-udm', 'CURRENT', 'OK'),
  },
  pduPower: {
    totalWatts: 143,
    metadata: metadata('fixture-unpoller-pdu-power', 'CURRENT', 'OK'),
  },
  lastSpeedTest: {
    downloadMbps: 941.6,
    uploadMbps: 38.7,
    latencyMs: 18.2,
    observedAt: '2026-07-19T09:00:00.000Z',
    metadata: metadata('fixture-unifi-speedtest', 'STALE', 'INFO', 'Historical result only; this interface cannot start a speed test.'),
  },
  metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
};

export const fixtureStorageBackups: StorageBackup[] = [
  {
    id: 'pbs-01-pve01-old-backup',
    name: 'pbs-01 / pve01-backups',
    capacityBytes: 500_000_000_000,
    usedBytes: 290_000_000_000,
    lastSuccessfulBackupAt: '2026-07-17T00:00:00.000Z',
    failureCount: 0,
    metadata: metadata('fixture-pbs', 'STALE', 'WARN', 'Last successful backup exceeds the configured age threshold.'),
  },
  {
    id: 'pbs-01-failed-backup',
    name: 'pbs-01 / failed-job',
    capacityBytes: 500_000_000_000,
    usedBytes: 290_000_000_000,
    lastSuccessfulBackupAt: null,
    failureCount: 2,
    metadata: metadata('fixture-pbs', 'CURRENT', 'CRIT', 'Two backup jobs have failed.'),
  },
  {
    id: 'pbs-01-pve02-backups',
    name: 'pbs-01 / pve02-backups',
    capacityBytes: 500_000_000_000,
    usedBytes: 210_000_000_000,
    lastSuccessfulBackupAt: '2026-07-19T03:00:00.000Z',
    failureCount: 0,
    metadata: metadata('fixture-pbs', 'CURRENT', 'OK'),
  },
  {
    id: 'pve-01-vmdata',
    name: 'pve-01 / vmdata',
    capacityBytes: 2_000_000_000_000,
    usedBytes: 1_550_000_000_000,
    lastSuccessfulBackupAt: null,
    failureCount: null,
    metadata: metadata('fixture-pbs', 'NO_DATA', 'INFO', 'Backup data does not apply to this storage row.'),
  },
];

export const fixtureStorage = {
  pbs: {
    datastore: 'pbs-01',
    reachable: true,
    metadata: metadata('fixture-pbs-probe', 'CURRENT', 'OK'),
  },
  policy: {
    backupWarningAgeSeconds: 86_400,
    backupFailureThreshold: 1,
  },
} as const;

export const fixtureServices: ServiceStatus[] = [
  {
    id: 'argocd',
    name: 'Argo CD',
    group: 'Infrastructure',
    description: 'GitOps control plane',
    href: 'https://argocd.lab.seandre.dev',
    status: 'UP',
    latencyMs: 12,
    metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
  },
  {
    id: 'grafana',
    name: 'Grafana',
    group: 'Infrastructure',
    description: 'Cluster dashboards',
    href: 'https://grafana.lab.seandre.dev',
    status: 'UP',
    latencyMs: 18,
    metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
  },
  {
    id: 'unifi',
    name: 'UniFi',
    group: 'Infrastructure',
    description: 'Network management',
    href: 'https://unifi.ui.com',
    status: 'DEGRADED',
    latencyMs: null,
    metadata: metadata('fixture-unifi', 'NOT_SUPPORTED', 'INFO', 'API capability requires verification.'),
  },
  {
    id: 'pve-01',
    name: 'pve-01',
    group: 'Host Status',
    description: 'Primary Proxmox host',
    href: 'https://pve-01.lab.seandre.dev:8006',
    status: 'UP',
    latencyMs: 8,
    metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
  },
  {
    id: 'pve-02',
    name: 'pve-02',
    group: 'Host Status',
    description: 'Standalone Proxmox host',
    href: 'https://pve-02.lab.seandre.dev:8006',
    status: 'DEGRADED',
    latencyMs: 20,
    metadata: metadata('fixture-service-probes', 'STALE', 'WARN', 'Last probe is 42 seconds old.'),
  },
  {
    id: 'bastion-01',
    name: 'bastion-01',
    group: 'Host Status',
    description: 'OKD infrastructure VM on pve-02',
    href: 'https://nexus.lab.seandre.dev',
    status: 'DOWN',
    latencyMs: null,
    metadata: metadata('fixture-service-probes', 'NO_DATA', 'WARN', 'No current reachability sample.'),
  },
  { id: 'cpu-temperature', name: 'CPU Temperature', group: 'Host Hardware', description: 'pve-01 CPU package temperature', href: 'https://pve-01.lab.seandre.dev:8006', status: 'UP', latencyMs: 8, metadata: metadata('fixture-service-probes', 'CURRENT', 'OK') },
  { id: 'system-nvme-temperature', name: 'System NVMe Temperature', group: 'Host Hardware', description: '256 GB system NVMe temperature', href: 'https://pve-01.lab.seandre.dev:8006', status: 'UP', latencyMs: 8, metadata: metadata('fixture-service-probes', 'CURRENT', 'OK') },
  { id: 'vmdata-nvme-temperature', name: 'VM Data NVMe Temperature', group: 'Host Hardware', description: '2 TB VM storage NVMe temperature', href: 'https://pve-01.lab.seandre.dev:8006', status: 'UP', latencyMs: 8, metadata: metadata('fixture-service-probes', 'CURRENT', 'OK') },
  { id: 'host-os-storage', name: 'Host OS Storage', group: 'Host Hardware', description: 'Proxmox root filesystem usage', href: 'https://pve-01.lab.seandre.dev:8006', status: 'UP', latencyMs: 8, metadata: metadata('fixture-service-probes', 'CURRENT', 'OK') },
  { id: 'vmdata-disk-io', name: 'VM Data Disk I/O', group: 'Host Hardware', description: '2 TB vmdata NVMe throughput', href: 'https://pve-01.lab.seandre.dev:8006', status: 'UP', latencyMs: 8, metadata: metadata('fixture-service-probes', 'CURRENT', 'OK') },
  { id: 'proxmox-network', name: 'Proxmox Network', group: 'Host Hardware', description: 'vmbr0 bridge traffic', href: 'https://pve-01.lab.seandre.dev:8006', status: 'UP', latencyMs: 8, metadata: metadata('fixture-service-probes', 'CURRENT', 'OK') },
  {
    id: 'homelab-docs',
    name: 'Homelab Docs',
    group: 'Apps',
    description: 'Infrastructure documentation and runbooks',
    href: 'https://docs.lab.seandre.dev',
    status: 'UP',
    latencyMs: 13,
    metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
  },
  {
    id: 'nginx-test',
    name: 'nginx test',
    group: 'Apps',
    description: 'Ingress test app',
    href: 'https://nginx-test.lab.seandre.dev',
    status: 'UP',
    latencyMs: 6,
    metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
  },
  {
    id: 'repository',
    name: 'Repository',
    group: 'Homelab',
    description: 'Homelab source repository',
    href: 'https://github.com/seandre/k8s-homelab',
    status: 'UP',
    latencyMs: null,
    metadata: metadata('fixture-bookmarks', 'CURRENT', 'INFO', 'Bookmark; reachability is not server-checked.'),
  },
  {
    id: 'homepage-github',
    name: 'Homepage GitHub',
    group: 'Homelab',
    description: 'Homepage project source and documentation',
    href: 'https://github.com/gethomepage/homepage',
    status: 'UP',
    latencyMs: null,
    metadata: metadata('fixture-bookmarks', 'CURRENT', 'INFO', 'Bookmark; replaces the previous Homepage Docs bookmark.'),
  },
  {
    id: 'okd-api',
    name: 'OKD API',
    group: 'Infrastructure',
    description: 'Read-only OKD cluster API',
    href: 'https://api.okd.lab.seandre.dev:6443',
    status: 'UP',
    latencyMs: 12,
    metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
  },
  {
    id: 'okd-console',
    name: 'OKD Console',
    group: 'Infrastructure',
    description: 'OKD cluster console',
    href: 'https://console-openshift-console.apps.okd.lab.seandre.dev',
    status: 'UP',
    latencyMs: 18,
    metadata: metadata('fixture-service-probes', 'CURRENT', 'OK'),
  },
];

export const fixtureWeather: Weather = {
  location: 'Portland, OR 97209',
  temperatureFahrenheit: 68,
  condition: 'Partly cloudy',
  sunrise: '2026-07-19T05:33:00.000-07:00',
  sunset: '2026-07-19T20:57:00.000-07:00',
  usAqi: 24,
  pm25: 4.1,
  pm10: 12.3,
  conditionsMetadata: metadata('fixture-open-meteo', 'CURRENT', 'OK'),
  airQualityMetadata: metadata('fixture-open-meteo-air', 'CURRENT', 'OK'),
  metadata: metadata('fixture-open-meteo', 'CURRENT', 'OK'),
};

export const healthyBootstrapFixture: Bootstrap = {
  schemaVersion: 5,
  generatedAt: FIXTURE_TIME,
  globalSeverity: 'WARN',
  alerts: fixtureAlerts,
  timeSeries: fixtureTimeSeries,
  hosts: fixtureHosts,
  clusters: fixtureClusters,
  workloads: fixtureWorkloads,
  platformOperators: fixturePlatformOperators,
  network: fixtureNetwork,
  storage: fixtureStorage,
  storageBackups: fixtureStorageBackups,
  services: fixtureServices,
  weather: fixtureWeather,
  indoor: healthyIndoorFixture,
};

export const stateFixtureExpectations = {
  healthy: 'CURRENT',
  warning: 'WARN',
  critical: 'CRIT',
  stale: 'STALE',
  noData: 'NO_DATA',
  notProvisioned: 'NOT_PROVISIONED',
  unsupported: 'NOT_SUPPORTED',
} as const;
