[proxmox]
pve-01 ansible_host=192.168.40.20

# Planned static addresses for the Homelab network.
[k3s_test]
k3s-test-01 ansible_host=192.168.40.21
[k3s_control]
k8s-control-01 ansible_host=192.168.40.21
[k3s_workers]
k8s-worker-01 ansible_host=192.168.40.22
k8s-worker-02 ansible_host=192.168.40.23
[utility]
utility-01 ansible_host=192.168.40.24
[k3s_cluster:children]
k3s_control
k3s_workers
[all:vars]
ansible_user=sean
ansible_python_interpreter=/usr/bin/python3
