apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/nginx-test
  - ../../../apps/homepage
  - ../../../apps/homepage-custom-preview
  - ../../../apps/kosync
  - ../../../apps/homelab-docs
  - ../../../apps/home-assistant
  - ../../../apps/cycling-calendar
