apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant-indoor-scrapeconfig.yaml
  - home-assistant-indoor-rules.yaml
  - homepage-host-exporters-scrapeconfig.yaml
  - unpoller-ca-configmap.yaml
  - unpoller-deployment.yaml
  - unpoller-service.yaml
  - unpoller-servicemonitor.yaml
  - unpoller-networkpolicy.yaml
