---
hpl_top500_upstream_repository: https://github.com/geerlingguy/top500-benchmark
hpl_top500_upstream_revision: e71588f33fcf358910047de25720e3147d627be4
hpl_mpich_version: "4.3.2"
hpl_mpich_archive_sha256: 47d774587a7156a53752218c811c852e70ac44db9c502dc3f399b4cb817e3818
hpl_mpich_source_url: >-
  https://github.com/pmodels/mpich/releases/download/v{{ hpl_mpich_version }}/mpich-{{ hpl_mpich_version }}.tar.gz
hpl_mpich_with_device: ch3:nemesis
hpl_openblas_version: "0.3.33"
hpl_openblas_revision: 62bcfb0dc9f1cfa685fc04135c50e2780c303137
hpl_openblas_repository: https://github.com/OpenMathLib/OpenBLAS.git
hpl_version: "2.3"
hpl_archive_sha256: 32c5c17d22330e6f2337b681aded51637fb6008d3f0eb7c277b163fadd612830
hpl_source_url: "https://www.netlib.org/benchmark/hpl/hpl-{{ hpl_version }}.tar.gz"
hpl_install_root: /opt/top500
hpl_compile_flags: "-flto=auto -O3 -march=x86-64-v3"
hpl_binary_path: "{{ hpl_install_root }}/tmp/hpl-{{ hpl_version }}/bin/top500/xhpl"
hpl_mpirun_path: "{{ hpl_install_root }}/mpich/bin/mpirun"
hpl_result_root: /var/lib/hpl-results
hpl_benchmark_user: hplbench
hpl_build_async_timeout: 7200
hpl_build_async_poll: 30
hpl_async_timeout: 14400
hpl_async_poll: 30
hpl_max_extra_runs: 2
hpl_cov_limit_percent: 3.0
hpl_capacity_memory_percent: 75
