apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cycling-calendar
  namespace: cycling-calendar
  labels:
    app.kubernetes.io/name: cycling-calendar
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cycling-calendar
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8080
  egress: []
