apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-indoor-actions
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage-custom
    app.kubernetes.io/component: control-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
